### ISSUE TITLE
Reword criteria about detecting whether  wallet was installed

### ISSUE THREAD

**Issue by kristovatlas** [OpenBitcoinPrivacyProject/wallet-ratings#108]
Current wording:

> The wallet application removal process eliminate all evidence that a wallet was previously installed

Too vague. Proposed new wording based on feedback from testers during testing phase of last report:

> When logged into the user who previously installed the wallet application or another user with default privileges, the user cannot detect that the wallet was previously installed once the application removal process is completed
> JSON comment: "This does not include non-standard accounts, such as admin accounts unlocked via rooted methods on mobile devices"

**Comment by kristovatlas** [comment]
ACK'd by @justusranvier and @crwatkins

**Comment by kristovatlas** [comment]
@dcousens recommends comment for OBPPV3-CR58: something like:

> Detectability can be observed both in-app and outside of it.

**Comment by dcousens** [comment]
Maybe as two different scoring points rather than a combination?

I'd wager in some cases you'll have both,  others only 1.
They certainly have 2 different levels of user competency associated.

**Comment by dcousens** [comment]
Scoring points:
- Detectability In-the-app
- Detectability Outside-the-app

Questions for both:
- Detectable that the wallet _application_ did/does exist?
- Detectable that [another users] account exists?
- Detectable that an account did previously exist?

**Comment by kristovatlas** [comment]
we talked tonight about different things an attacker might try to find things out inside the app and outside of it -- I will make a PR with some new/reworded criteria in this area to look at next week

**Comment by kristovatlas** [comment]
Above we have discussed two changes to the threat model with respect to forensic attacks:
1. Distinguish between in-app vs out-app interrogation of the device.
2. Add a criterion related to initializing the wallet with a random wallet data file to make it difficult to distinguish from a used, encrypted wallet data file.

Here are the existing attacks, countermeasures, and criteria related to forensics:
- 8f2926c6d9443fb47d9f2a30c489d6403c2a1fcd8ce9aea6e60a89f1c43127cb
  : Detect the existence of a wallet on a device
  - OBPPV3/CM44 (aa2d6bd66f83cb7a65af511cfc42990d3d41008bf7820782f376de197a8dac06
    ): Install the application is such a way that it is not detectable unless user performs a series of actions unlikely to be duplicated by an unauthorized user
    - OBPPV3/CR57 (bd525d9750a9e913d662da987b41b4327692073df4fa08a7e9729202d21a2d33
      ): The wallet application is difficult to detect as being installed unless the user performs a series of actions unlikely to be duplicated by an unauthorized user
  - OBPPV3/CM45 (42517f9cb000b8d3951bede96702be8b7602222b7fcc014a2fa661be1616c757
    ): The user can easily erase the application and all its metadata if the decide to stop using the wallet or device
    - OBPPV3/CR54 (e157bce4222167924c532205b40a7992a3ac1f1f9de36a4f9980e5281c033ad3
      ): Number of clicks needed to permanently and completely erase the wallet from a device
    - OBPPV3/CR55 (b5f8660f835d1738b73d8c65e14a0164a00e731bb0176688ab80a998efc4670e
      ): Number of clicks needed to permanently and completely remove the wallet application from a device
    - OBPPV3/CR58 (01cbe777a3abea219a15924080a4110a99c7c49057c9f5c274ea99dfc9b9dfef
      ): When logged into the user who previously installed the wallet application or another user with default privileges, the user cannot detect that the wallet was previously installed once the application removal process is completed
    - OBPPV3/CR59 (cae67a1a0304b1a9f30d194953f0470146d82a5a26a194bc915ed2e6d322b69b
      ): The wallet deletion process eliminates all evidence that a wallet was previously installed
  - OBPPV3/CM46 (93fc4fa4ef965850e225bb78a94d5ef31988d1428f8f3bd7da7661c05003f61a
    ): If user loses physical control over the device, the wallet can be deleted via remote command
    - OBPPV3/CR56 (05b2d6604ec7520f9eb45b3d18bb04340f8cb415a4516e31b76e22c9fcd0cd7b
      ): Wallet data can be remotely deleted by the user in the event the device containing the wallet is lost or stolen
  - OBPPV3/CM47 (58354b2f6f1e794e63bd1844c71c5810fd40140e7553f02def06c8ad75d02543
    ): Persistent wallet data is stored in a fashion that is not identifiable as belonging to a Bitcoin wallet
    - OBPPV3/CR60 (d8d82a51f925703305d00cef69fc624bb92b12d9c134c1df04ec597a6f803c7c
      ): Persistent wallet metadata is stored in a form not identifiable as belonging to a Bitcoin wallet
- 66f0b4991fd97d00ea920c2fe216e65e3f80eacd0a3b2f0452217292a937b947: Perform forensic analysis on a device, searching for sensitive information about a wallet
  - OBPPV3/CM48 (b5703eb1bd5e6a3737bb4508b7ed82ae7d1f6f84a453b7b0391547f515b34c47
    ): Encrypt all public keys in the wallet
    - OBPPV3/CR52 (baf5bdb47105a1f98ddf51b9852062722ae5387e835a03038f52bdfed5c68824
      ): Number of clicks to set an encryption password/PIN for wallet public keys (apart from that needed to encrypt private keys)
  - OBPPV3/CM49 (a26e95124a6cd89280fa1ac1d32816688c2a31614581fb62fbaedc95068c6155
    ): Encrypt all non-keypair wallet metadata
    - OBPPV3/CR53 (c55c394d7fdb867a2dd83dff73e5416e2585057586302c2256e8a6f8dc9ae651): Number of clicks to set an encryption password/PIN for non-keypair wallet metadata (apart from that needed to encrypt private keys)

I in accordance with the proposed changes I propose that we :
1. Split OBPPV3/CR54 and OBPPV3/CR55 into 2 more criteria each and re-word descriptions for CR58 and CR59.
2. Add a criterion.

The end result would be (changes in bold):
- 8f2926c6d9443fb47d9f2a30c489d6403c2a1fcd8ce9aea6e60a89f1c43127cb
  : Detect the existence of a wallet on a device
  - OBPPV3/CM44 (aa2d6bd66f83cb7a65af511cfc42990d3d41008bf7820782f376de197a8dac06
    ): Install the application is such a way that it is not detectable unless user performs a series of actions unlikely to be duplicated by an unauthorized user
    - OBPPV3/CR57 (bd525d9750a9e913d662da987b41b4327692073df4fa08a7e9729202d21a2d33
      ): The wallet application is difficult to detect as being installed unless the user performs a series of actions unlikely to be duplicated by an unauthorized user
  - OBPPV3/CM45 (42517f9cb000b8d3951bede96702be8b7602222b7fcc014a2fa661be1616c757
    ): The user can easily erase the application and all its metadata if the decide to stop using the wallet or device
    - **OBPPV3/CR54: Number of clicks to delete the wallet within the wallet client (re-wording of CR54)**
    - **New CR: A user who opens the wallet client cannot determine whether a wallet was ever registered on this device once the wallet deletion process has been completed.**
    - **A person logged in as the user who created the wallet or another user on the same system with default system privileges cannot determine whether a wallet was ever wallet registered not his device once the wallet deletion process has been completed. (re-wording of CR59)**
    - **OBPPV3/CR55: Number of clicks to remove the wallet client from a device (re-wording of CR55)**
    - **New CR: A user who re-installs the wallet client cannot determine whether the app was previously installed from within the application itself.**
    - **OBPPV3/CR58: A person logged in as the user who previously installed the wallet or another user on the same system with default system privileges cannot determine whether the wallet client was ever installed this device once uninstalled. (re-wording of CR58) Comment: This would include accessing the operating system’s App Store or package manager to review which apps have been previously downloaded.**
    - **NEW Criterion: description: “When the application is installed, all wallet metadata is initialized in such a way that a newly installed wallet client cannot be distinguished from a wallet client that has been used to send and/or receive bitcoin. comment: A wallet client can achieve this, for example, by initializing wallet metadata files with random data that cannot be distinguished from encrypted data.**
  - OBPPV3/CM46 (93fc4fa4ef965850e225bb78a94d5ef31988d1428f8f3bd7da7661c05003f61a
    ): If user loses physical control over the device, the wallet can be deleted via remote command
    - OBPPV3/CR56 (05b2d6604ec7520f9eb45b3d18bb04340f8cb415a4516e31b76e22c9fcd0cd7b
      ): Wallet data can be remotely deleted by the user in the event the device containing the wallet is lost or stolen
  - OBPPV3/CM47 (58354b2f6f1e794e63bd1844c71c5810fd40140e7553f02def06c8ad75d02543
    ): Persistent wallet data is stored in a fashion that is not identifiable as belonging to a Bitcoin wallet
    - OBPPV3/CR60 (d8d82a51f925703305d00cef69fc624bb92b12d9c134c1df04ec597a6f803c7c
      ): Persistent wallet metadata is stored in a form not identifiable as belonging to a Bitcoin wallet
- 66f0b4991fd97d00ea920c2fe216e65e3f80eacd0a3b2f0452217292a937b947: Perform forensic analysis on a device, searching for sensitive information about a wallet
  - OBPPV3/CM48 (b5703eb1bd5e6a3737bb4508b7ed82ae7d1f6f84a453b7b0391547f515b34c47
    ): Encrypt all public keys in the wallet
    - OBPPV3/CR52 (baf5bdb47105a1f98ddf51b9852062722ae5387e835a03038f52bdfed5c68824
      ): Number of clicks to set an encryption password/PIN for wallet public keys (apart from that needed to encrypt private keys)
  - OBPPV3/CM49 (a26e95124a6cd89280fa1ac1d32816688c2a31614581fb62fbaedc95068c6155
    ): Encrypt all non-keypair wallet metadata
    - OBPPV3/CR53 (c55c394d7fdb867a2dd83dff73e5416e2585057586302c2256e8a6f8dc9ae651): Number of clicks to set an encryption password/PIN for non-keypair wallet metadata (apart from that needed to encrypt private keys)

**Comment by kristovatlas** [comment]
Wording needs to be fixed.

**Comment by dcousens** [comment]
May be easiest to just frame the questions in terms of https://github.com/OpenBitcoinPrivacyProject/wallet-ratings/issues/108#issuecomment-239041625?

**Comment by kristovatlas** [comment]
Updated with changes in italics:
- 8f2926c6d9443fb47d9f2a30c489d6403c2a1fcd8ce9aea6e60a89f1c43127cb: Detect the existence of a wallet on a device
  - OBPPV3/CM44 (aa2d6bd66f83cb7a65af511cfc42990d3d41008bf7820782f376de197a8dac06): Install the application is such a way that it is not detectable unless user performs a series of actions unlikely to be duplicated by an unauthorized user
    - OBPPV3/CR57 (bd525d9750a9e913d662da987b41b4327692073df4fa08a7e9729202d21a2d33): The wallet application is difficult to detect as being installed unless the user performs a series of actions unlikely to be duplicated by an unauthorized user
  - OBPPV3/CM45 (42517f9cb000b8d3951bede96702be8b7602222b7fcc014a2fa661be1616c757): The user can easily erase the application and all its metadata if the decide to stop using the wallet or device
    - _**OBPPV3/CR54: Number of clicks to delete wallet data within the wallet client (re-wording of CR54)**_
    - **New CR: A user who opens the wallet client cannot determine whether a wallet was ever registered on this device once the wallet deletion process has been completed.**
    - _**A person logged in as the user who created the wallet or another user on the same system with default system privileges cannot determine whether the wallet application was used to send funds or receive funds once the wallet deletion process has been completed. (re-wording of CR59)**_
    - **OBPPV3/CR55: Number of clicks to remove the wallet client from a device (re-wording of CR55)**
    - **New CR: A user who re-installs the wallet client cannot determine whether the app was previously installed from within the application itself.**
    - **OBPPV3/CR58: A person logged in as the user who previously installed the wallet or another user on the same system with default system privileges cannot determine whether the wallet client was ever installed this device once uninstalled. (re-wording of CR58) Comment: This would include accessing the operating system’s App Store or package manager to review which apps have been previously downloaded.**
    - **NEW Criterion: description: “When the application is installed, all wallet metadata is initialized in such a way that a newly installed wallet client cannot be distinguished from a wallet client that has been used to send and/or receive bitcoin. comment: A wallet client can achieve this, for example, by initializing wallet metadata files with random data that cannot be distinguished from encrypted data.**
  - OBPPV3/CM46 (93fc4fa4ef965850e225bb78a94d5ef31988d1428f8f3bd7da7661c05003f61a
    ): If user loses physical control over the device, the wallet can be deleted via remote command
    - OBPPV3/CR56 (05b2d6604ec7520f9eb45b3d18bb04340f8cb415a4516e31b76e22c9fcd0cd7b
      ): Wallet data can be remotely deleted by the user in the event the device containing the wallet is lost or stolen
  - OBPPV3/CM47 (58354b2f6f1e794e63bd1844c71c5810fd40140e7553f02def06c8ad75d02543
    ): Persistent wallet data is stored in a fashion that is not identifiable as belonging to a Bitcoin wallet
    - OBPPV3/CR60 (d8d82a51f925703305d00cef69fc624bb92b12d9c134c1df04ec597a6f803c7c
      ): Persistent wallet metadata is stored in a form not identifiable as belonging to a Bitcoin wallet
- 66f0b4991fd97d00ea920c2fe216e65e3f80eacd0a3b2f0452217292a937b947: Perform forensic analysis on a device, searching for sensitive information about a wallet
  - OBPPV3/CM48 (b5703eb1bd5e6a3737bb4508b7ed82ae7d1f6f84a453b7b0391547f515b34c47
    ): Encrypt all public keys in the wallet
    - OBPPV3/CR52 (baf5bdb47105a1f98ddf51b9852062722ae5387e835a03038f52bdfed5c68824
      ): Number of clicks to set an encryption password/PIN for wallet public keys (apart from that needed to encrypt private keys)
  - OBPPV3/CM49 (a26e95124a6cd89280fa1ac1d32816688c2a31614581fb62fbaedc95068c6155
    ): Encrypt all non-keypair wallet metadata
    - OBPPV3/CR53 (c55c394d7fdb867a2dd83dff73e5416e2585057586302c2256e8a6f8dc9ae651): Number of clicks to set an encryption password/PIN for non-keypair wallet metadata (apart from that needed to encrypt private keys)

**Comment by dcousens** [comment]
>  person logged in as the user who created the wallet**,** or another user on the same system with default system privileges cannot determine whether the wallet application was used to **send or receive funds after** the wallet deletion process has been completed. (re-wording of CR59)

IMHO

**Comment by dcousens** [comment]
> OBPPV3/CR55: Number of clicks to remove the wallet client from a device (re-wording of CR55)

This could vary O/S to O/S,  or even model to model (think of developers targeting Android 4+,  but Samsung might have a custom uninstaller etc).

**Comment by dcousens** [comment]
> When the application is installed, all **application** metadata is initialized in such a way that **it** cannot be distinguished from **an application that has been** used **extensively**. comment: **An application** can achieve this, for example, by initializing **application metadata** with random data that is **indistinguishable** from encrypted data.

IMHO

**Comment by dcousens** [comment]
ACK https://github.com/OpenBitcoinPrivacyProject/wallet-ratings/issues/108#issuecomment-240917959,  but some suggested edits above (personally).

**Comment by kristovatlas** [comment]
> This could vary O/S to O/S, or even model to model (think of developers targeting Android 4+, but Samsung might have a custom uninstaller etc).

Yes, some of our metrics vary across operating systems at least -- maybe models. I don't know of a way to avoid this. It does not strike me as important to try to avoid. It might be helpful to document which model testing is performed on, but so far there haven't been any model-specific discrepancies in the past two reports despite the fact that at least two testers evaluate each wallet and are not standardizing make, model, or even the OS version.
