### ISSUE TITLE
de-list the "# of mixing partners" criteria from countermeasure for "risk-free mixing"

### ISSUE THREAD

**Issue by kristovatlas** [OpenBitcoinPrivacyProject/wallet-ratings#109]
Currently this countermeasure:

> Use mixing methods that do not allow for theft of funds

Under this attack:

> Users may avoid mixing if mixing services can steal funds

Has 2 criteria:

> Average number of other users whose funds are mixed with the client user's when sending through a mixing process
> 
> Mixing is secure against theft of funds

The first one is not relevant. Remove it.

**Comment by kristovatlas** [comment]
@justusranvier and @crwatkins have ACK'd removing CR19 from that countermeasure.

**Comment by dcousens** [comment]
ACK
