### ISSUE TITLE
rename countermeasure concerning querying blockchain data for multiple addresses

### ISSUE THREAD

**Issue by kristovatlas** [OpenBitcoinPrivacyProject/wallet-ratings#110]
Current wording:

> Obtain relevant blockchain data without making queries to other network participants

Proposed new wording:

> Perform multiple queries for blockchain data in a way that makes it difficult to correlate the queries with one another

The criteria that apply to this countermeasure are as follows, prompting the rewording:

> Balance information is obtained without making queries to other network participants
> Balance information is obtained by making queries to other network participants that do not include multiple addresses in a specific connection context
> Avoids including addresses from multiple identity containers in the same balance query
> Balance information is obtained via a method that matches a fraction of the blockchain beyond the addresses belonging to the wallet
> Avoids including addresses from multiple identity containers in the same balance query

Alternatively, we could break up the current countermeasure into multiple countermeasures.

**Comment by kristovatlas** [comment]
Let's retain this countermeasure:

> Obtain relevant blockchain data without making queries to other network participants

re-word criteria:

> Balance information is obtained without making queries to other network participants

to:

> Balance information is obtained through a local copy of the blockchain.

Add a new one:

> Perform multiple queries for blockchain data in a way that makes it difficult to correlate the queries with one another

All other criteria will fall under this. ACK'd by @justusranvier and @crwatkins in meeting

**Comment by dcousens** [comment]
ACK on all

**Comment by crwatkins** [comment]
ACK
