### ISSUE TITLE
Revisit criterion for number of clicks to perform first backup

### ISSUE THREAD

**Issue by kristovatlas** [OpenBitcoinPrivacyProject/wallet-ratings#111]
OBPPV3-CR61 is:

> Number of clicks to create the first wallet backup

This is currently only used as a criterion for OBPPV3-CM56:

> Use eternal backups

Under this attack:

> Users may reuse non-ECDH addresses due to the fear of losing funds if avoiding reuse increases the risk that wallet backups will become unexpectedly invalid

The other criterion under that countermeasure is OBPPV3-CR62:

> Number of clicks needed to update an existing backup due to the creation of a new receiving or change address

CR61 doesn’t seem relevant to the privacy properties of eternal backups; you’re equally screwed whether you reuse addresses or not if you do 0 backups. CR62 does properly capture the intention of the countermeasure, IMHO.

If others agree, we can simply delete this criterion.

**Comment by dcousens** [comment]
Happy to delete

**Comment by crwatkins** [comment]
Good to delete.
