### ISSUE TITLE
Revisit criterion for number of clicks to import a private key into an identity container

### ISSUE THREAD

**Issue by kristovatlas** [OpenBitcoinPrivacyProject/wallet-ratings#112]
OBPPV3-CR45 is:

> Number of clicks to assign an imported private key into an identity container

It is only assigned to one countermeasure/attack:

> Use multiple identities/accounts to allow funds associated with one transaction participant to be kept apart from funds associated with a different transaction participant
> Collude with other transaction participants to infer a bitcoin user's behavior based on the flow of funds from one colluding entity, to the targeted user, to another colluding entity

There is another, better criteria already listed under that countermeasure, OBPPV3-CR44:

> Number of clicks to create a new identity container from the home screen of an existing identity container

Problems with OBPPV3-CR45 were highlighted during our last edition testing phase. It’s not possible to accomplish this goal in zero clicks, it’s ostensibly a corner case, and just overall not a well-formed measurement of privacy.

I suggest we simply delete it.

**Comment by kristovatlas** [comment]
@crwatkins suggests maybe replacing this criterion with another one in the future that is conceptually similar

**Comment by dcousens** [comment]
I'm up for just deleting it. :+1:

**Comment by crwatkins** [comment]
ACK
