### ISSUE TITLE
Anti-fee sniping counter-measures

### ISSUE THREAD

**Issue by dcousens** [OpenBitcoinPrivacyProject/wallet-ratings#115]
Anti-fee sniping is the act of setting `nLockTime` to the current block height such that it discourages a miner to perform a re-org.

Quote from @petertodds commit (https://github.com/bitcoin/bitcoin/commit/db6047d61b742be07442f891e70570b791c585e3, pull request https://github.com/bitcoin/bitcoin/pull/6216)

> ```
> // A simple way to think about this is from the wallet's point of view we
>  // always want the blockchain to move forward. By setting nLockTime this
>  // way we're basically making the statement that we only want this
>  // transaction to appear in the next block; we don't want to potentially
>  // encourage reorgs by allowing transactions to appear at lower heights
>  // than the next block in forks of the best chain.
> ```

Does this have any privacy implications?

AFAIK,  at the time of transaction creation,  it doesn't (provided this process is universally adapted obviously).

However,  as expressed in [this reddit thread](https://www.reddit.com/r/Bitcoin/comments/4v28jl/how_have_fungiblity_problems_affected_you_in/d5uvs37) by /u/archebaldbane,  the creation of these transactions with a **delayed broadcast** causes a significant privacy concern due to the extra information encoded in the transaction (namely,  at what block height it was originally created).

I therefore think,  at least in the above case, that there is privacy implications to the anti-fee sniping feature... however,  it is obviously just a side effect of the fact that the broadcasting is delayed. 

Thoughts?
Do we need to consider this at all?

**Comment by dcousens** [comment]
ping @kristovatlas

**Comment by dcousens** [comment]
This was also brought up by @TheBlueMatt at _Scaling Bitcoin_: https://youtu.be/8BLWUUPfh2Q?t=1952

**Comment by kristovatlas** [comment]
The sequence and locktime values used to accomplish this make Bitcoin-Qt much more easily fingerprinted, which is what @TheBlueMatt said.

I think this is a pretty minor info leak for wallets that don't delay broadcast, which is almost all of them, or all of them. However, this would obviously foil delayed broadcasts.

I propose that we have a fee sniping question in our 3rd edition wallet provider questionnaire, and circle back to the issue of broadcast delays for 4th edition since we're not currently aware of any such wallets.

(Note to self: Once questionnaire component is complete, remove that tag, bump to 4th edition, and add attack, countermeasure, and criteria tags.)

**Comment by dcousens** [comment]
Agreed.

I think for now its relevant solely from a point of view of `nLockTime` being rare.
From a "whole blockchain" point of view.

```
Transactions:   152792786
-- Inputs:      395842358 (ratio 2.59071)
-- Outputs:     438145182 (ratio 2.86758)
-- Version1:    152792719 (100%)
-- Version2:    61 (3.99234e-05%)
-- Locktimes (>0):      13552196 (8.86966%)
```

Having a `nLockTime != 0` would liken you to 8.87% of all transactions **ever**.
However, in the last ~19000 blocks:

```
Transactions:   2988181
-- Inputs:      7004734 (ratio 2.34415)
-- Outputs:     7412505 (ratio 2.48061)
-- Version1:    2988181 (100%)
-- Version2:    0 (0%)
-- Locktimes (>0):      510378 (17.0799%)
```

You'd be akin to 17.08% of all transactions.

Source: https://github.com/dcousens/fast-dat-parser/blob/master/functors.hpp#L157-L166

real    6m7.767s
user    2m23.487s
sys     1m17.160s

**Comment by TheBlueMatt** [comment]
Ultimately this is one of the privacy things where it sucks that only one or two wallets do this, but if you're gonna make a recommendation, ideally you would recommend that wallets do this. While its relatively limited, it is some small dent in long-term incentive incompatibility.

**Comment by dcousens** [comment]
This is captured by https://github.com/OpenBitcoinPrivacyProject/threat-model-scoring-system/blob/reorg-to-scoring-system/obpp3.hjson#L699

>  Avoid communicating state-based information to other entities which could be used to uniquely identify the client

But from a blockchain attacker,  not network observer

**Comment by kristovatlas** [comment]
@TheBlueMatt: Just to clarify, we're not looking to make recommendations with these threat model elements, but to measure the current state of affairs.

**Comment by kristovatlas** [comment]
For posterity, Daniel is referring to CM30:
```
  #Network Observer Attack 11 of 16
                    numeral: K
                    name: Correlate activity of a specific wallet across different connection sessions by observing idiosyncratic client wallet behavior which acts as a unique fingerprint
                    weight: 0
                    nonce-id: 277ec132f4cb4edc1cffc0905bde99fe5d6453f368661ff9aad87d1fca34662a
                    countermeasures: [{
                            numeral: "1"
                            id: OBPPV3/CM30
                            description: Avoid communicating state-based information to other entities which could be used to uniquely identify the client
                            effectiveness: 0
                            criteria: [{
                                    numeral: a
                                    id: OBPPV3/CR180
                                    description: The wallet client does not send stateful information in messages that persists between connection contexts
                                    effectiveness: 0 }]}]}{
```

Should we add a relevant attack/countermeasure for blockchain observer attacker as well for 4th edition, @dcousens ?

**Comment by dcousens** [comment]
@kristovatlas absolutely,  this is the recording of a wallets stateful information into the blockchain through a transaction (through means other than the selected inputs).

**Comment by kristovatlas** [comment]
TODO: list CM30 under an appropriate Blockchain Observer attack

**Comment by dcousens** [comment]
Was this added?
