### ISSUE TITLE
Metric: Transaction creation and signing code is open source

### ISSUE THREAD

**Issue by kristovatlas** [OpenBitcoinPrivacyProject/wallet-ratings#13]
As @sergiodemianlerner pointed out on Twitter<sup>1</sup>, it's important to look out for covert channels of leaking security- or privacy-sesitive information. We should add a metric for whether the code that drafts and signs trasnactions is open source and therefore readily auditable. I imagine most wallets will pass this metric.

<sup>1</sup>: https://twitter.com/sdlerner/status/599363508682240000

**Comment by schildbach** [comment]
Perhaps it should even be valued if the source is free software: projects that are open source but using restricted licenses tend to have less peers than free software projects.

**Comment by justusranvier** [comment]
We need to think about how this fits into the threat model.

**Comment by JeremyRand** [comment]
Would also be interesting to consider reproducible builds, since otherwise the source code is only useful if the users builds from source (which almost no one does in practice).

**Comment by schildbach** [comment]
I agree with @JeremyRand

**Comment by kristovatlas** [comment]
Also agree with @JeremyRand and @schildbach about reproducible builds. Thanks for the suggestion.

**Comment by kristovatlas** [comment]
Add 2 countermeasures:
-open source
-reproducible build such that user can build the binary and end up with identical binary

**Comment by kristovatlas** [comment]
Criteria: Non-obfuscated source code is available for immediate inspection.
Criteria: Simple instructions for building the source code are provided.
Criteria: Clear instructions are provided for the user to produce a compiled version that exactly matches the binary distributed by the wallet provider.

**Comment by kristovatlas** [comment]
A criterion exists for this now, OBPPV3/CR70 (2962fa537ab4b70651f21a2d0a8c82c9ad5668663d72755f67d414fb17e2a3f5):

> Non-obfuscated source code for the wallet application is available for immediate inspection

**Comment by kristovatlas** [comment]
Other related criteria that exist that were alluded to above:

``` json
{
"id": "OBPPV3/CR69",
            "description": "The wallet provider supplies simple instructions for building a usable binary from the source code",
            "nonce-id": "c6c4523648996a95d3d9436aeff46b11c85cd46765d1df1ace370438754f5855"
}
```

and 

``` json
 {
            "id": "OBPPV3/CR71",
            "description": "A user can produce a compiled version of the application from the public source code that exactly matches the version distributed by the wallet provider",
            "nonce-id": "7c4c9f038599edcac718ab458c88621c89c0e2a83eb2798f37d2db6f016d80a1"
        }
```

**Comment by kristovatlas** [comment]
Thanks for the feedback @schildbach and @JeremyRand
