### ISSUE TITLE
"Identity separation" criterium

### ISSUE THREAD

**Issue by schildbach** [OpenBitcoinPrivacyProject/wallet-ratings#18]
I think the criterium for being able to manage multiple identities should be fulfilled also when the OS allows to switch users (like Android does for example). The reason is you'd better manage identities OS-globally anyways. Payment almost always involves more communication via e-mail, chat or web browser. If those apps don't switch identities at the same time as the wallet does, you'll link your identities and separation becomes worthless.

Actually I'd value OS-level identitity management higher than app-level.

**Comment by justusranvier** [comment]
That's an interesting approach.

I'm not sure how many users are currently aware of OS-level identity management capabilities.

**Comment by schildbach** [comment]
The ability to switch users reaches back to Android 4.2. On Android 5 and above, there is a big cyan-colored "switch user" icon in the top right corner of the quick settings.

![device-2015-05-26-005323](https://cloud.githubusercontent.com/assets/743306/7802925/b93bd50a-0341-11e5-9c83-83063e008eca.png)

**Comment by kristovatlas** [comment]
Let's include this as a method of identity separation and count clicks.

**Comment by kristovatlas** [comment]
The relevant criterion in use is

``` json
        {
            "id": "OBPPV3/CR44",
            "description": "Number of clicks to create a new identity container from the home screen of an existing identity container",
            "nonce-id": "bf25cd7e62ecc64aa5fd964c579a9a3c9a2617b7cf1aa3ee9ed6eafbca5cdc6c"
        }
```
