### ISSUE TITLE
add attacker to threat model: wallet provider

### ISSUE THREAD

**Issue by kristovatlas** [OpenBitcoinPrivacyProject/wallet-ratings#21]
wallet provider can:
- ship malicious binaries
  - countermeasure: users can build binary themselves
  - countermeasure: build system is deterministic, allowing multiple builders to build the same binary and sign them

**Comment by justusranvier** [comment]
Related: #13

**Comment by justusranvier** [comment]
Attack: The wallet can not be used without supplying personally identifying information

**Comment by justusranvier** [comment]
Attack: The wallet may transmit usage and/or debug data back to the provider which can be used to correlate transactions to a particular user.

**Comment by justusranvier** [comment]
Countermeasures:
- Don't collect PII
- Only send debug information if users opt-in and are allowed to review the information before being sent
- Allow debug/usage information to be sent over Tor

**Comment by kristovatlas** [comment]
All of the stuff mentioned in this issue is now included in the threat model. Closing.
