### ISSUE TITLE
break network peer attackers into 2 kinds of attackers

### ISSUE THREAD

**Issue by kristovatlas** [OpenBitcoinPrivacyProject/wallet-ratings#22]
- protocol-level peers
  - annotate with examples:
    - global passive adversary (e.g. NSA): can see most of connections at once
    - sybil attacker (e.g. chainalysis) tries to coerce connections
    - peer(s) designated for communication. may be a monolithic server, federated server, light clight, or full node peer.
- network-level peer
  - annotate with examples:
    - ISP
    - Tor nodes
    - VPN

**Comment by justusranvier** [comment]
Attack: Link addresses belonging to a single user by observing information leaked by the wallet in the process of obtaining its balance information from the network 

Countermeasures:
- Obtain balance information without making queries to other network participants
- Only query one address at a time from a specific connection context
- Query multiple addresses at once using a technique that includes false positives

**Comment by justusranvier** [comment]
Need an rating method that's the inverse of the "number of clicks" formula

**Comment by justusranvier** [comment]
Full node: maintains a complete copy of the blockchain such that queries to external sources are not needed to obtain balance information

**Comment by kristovatlas** [comment]
Client does not lookup more than one address balance query per connection context.
