### ISSUE TITLE
add attacks: fingerprint wallet client using blockchain or network data

### ISSUE THREAD

**Issue by kristovatlas** [OpenBitcoinPrivacyProject/wallet-ratings#26]
attacker can, e.g. perform many transactions and observe behavior, then build statistical model using machine learning.

**Comment by justusranvier** [comment]
attack: A blockchain observer can derive the type of wallet used to create a transaction by observing idiosyncrasies in the manner in which the transaction was composed

**Comment by justusranvier** [comment]
attack: A network observer can derive the type of wallet used to create a transaction by observing idiosyncrasies in the interactive behaviour of the wallet

**Comment by justusranvier** [comment]
attack: A protocol peer can derive the type of wallet used to create a transaction by actively probing the wallet to discover  idiosyncrasies in the interactive behaviour of the wallet

**Comment by justusranvier** [comment]
Replaces #3

**Comment by kristovatlas** [comment]
another example of a distinctive blockchain fingerprint https://www.evernote.com/shard/s50/sh/b809834d-60b4-40bf-88b0-bdb64c7edee1/0a3f71864c6fed47/deep/0/

**Comment by kristovatlas** [comment]
Network attacker: Can use user agent. See:
https://en.bitcoin.it/wiki/Protocol_documentation
https://github.com/bitcoin/bips/blob/master/bip-0014.mediawiki

**Comment by justusranvier** [comment]
countermeasure:
- use a standardized ordering of inputs and outputs
- avoid routinely creating outputs that are identifiable by their size or script
- avoid using one distinctive user agent when connecting to the Bitcoin network
- avoid using a non-Bitcoin network protocol that leaks information about the type of client in use.

**Comment by kristovatlas** [comment]
Criteria: Does the tx send a donation with a known output size or known address?

**Comment by kristovatlas** [comment]
Criteria: Is the donation feature automatic (Multibit) or manual?

**Comment by kristovatlas** [comment]
Criteria: Do you use a common UA (e.g. Bitcoin Core)
OR
Do you use a random UA from a list of possible UAs?

**Comment by kristovatlas** [comment]
Criteria: Do you make an HTTP connection to a known wallet provider's domain?

**Comment by kristovatlas** [comment]
Criteria: BIP 69 compliant?

**Comment by kristovatlas** [comment]
Current covered in the threat model:
- Network Observer attack: Derive the type of wallet used to create a transaction by passively observing idiosyncrasies in the interactive behaviour of the wallet
  - CM28: Avoid using one distinctive user agent when connecting to the Bitcoin network
    - CR38: The wallet connects to the network using an unremarkable user agent
    - CR39: The wallet connects to the network using a random user agent, from a set of unremarkable user agents, for each connection
  - CM29: Avoid using a non-Bitcoin network protocol that leaks information about the type of client in use
    - CR37: The wallet avoids observably connecting to a known endpoint, such as a wallet provider's domain

The criteria proposed above in previous comments have been included under blockchain observer attacks, where they fit better since they do not leak any information at the network observer level that is not leaked at the more accessible blockchain observer level.
