### ISSUE TITLE
Software Exposure

### ISSUE THREAD

**Issue by ghost** [OpenBitcoinPrivacyProject/wallet-ratings#3]
Something that might be of value to mention in this document is that most wallet software today leaks it's identity through the transactions it creates. In a large number of cases it's possible to observe a cluster of related transactions and build up a pretty good idea of the client which is in use. In my experience over half of all transactions can be nailed down to a particular piece of software simply by just observing data available in the block chain. While not particularly identifying in itself, information about the type of software used can be used to refute possible associations between clusters.

**Comment by kristovatlas** [comment]
That's really interesting. If I understand correctly, you're talking about a wallet client fingerprint on the blockchain, and presumably it could also have a distinctive network fingerprint as well.

**Comment by ghost** [comment]
Yes. You can often map a transaction to the software which made it, or at least cut it down to one of a small subset. Network fingerprints are something different altogether, you can tie a particular Bitcoin Core node to an address by using transaction baits (tricking the node to reveal it's ownership of an address), but this has fairly low utility as most wallets won't be listening for network connections.

**Comment by kristovatlas** [comment]
We need some more time to think about how this could be turned into a measurable metric. Aiming for Q2
