### ISSUE TITLE
When receiving funds, does wallet send automatic email to let the user know?

### ISSUE THREAD

**Issue by kristovatlas** [OpenBitcoinPrivacyProject/wallet-ratings#42]
Email may contain specific info. A general email may reveal what block the tx was first confirmed within.

**Comment by kristovatlas** [comment]
The contents of the email could be PGP encrypted. The subject could be generic and replicate the subject of other emails received from the wallet provider.

**Comment by kristovatlas** [comment]
new attack (network attacker): obtain information about a specific individual's transaction based on out-of-band notifications subsequent to a transaction (e.g. email you've got bitcoin!). Could be timing related or not, depending on the contents of the notification. Could be about sending or receiving funds.

**Comment by kristovatlas** [comment]
Proposed countermeasure to above attack: Abstain from sending out-of-band notifications outside of the wallet client when user sends or receive funds.

Proposed countermeasure to above attack: Encrypt out-of-band notifications outside of the wallet client when user sends or receive funds. This is weak since the sending of a encrypted message may be time-correlated with recent transactions on the blockchain. While there is a significant number of transactions taking place on the network at all times, additional context may allow an attacker to eliminate much of that volume as candidate transactions to match to the victim.

**Comment by kristovatlas** [comment]
This issue has two dangling countermeasures with no criteria.
- Network observer attack: Identify an entity as a likely transaction participant by observing out-of-band notifications subsequent to a transaction generated by any participant and/or their wallet provider
  - CM33: Do not transmit out-of-band notifications to a user when a transaction has been received
    - (no criteria)
  - CM34: Transmit out-of-band notifications via a method that is not detectable to a network observer
    - (no criteria)

I propose these criteria, one per countermeasure:
1. The wallet provider does not send out-of-band notifications to the user when a transaction has been added to a mempool or mined that involves the user’s funds. (JSON Comment: Out-of-band notification channels include email and push notifications to mobile devices.)
2. The wallet provider sends out-of-band notifications which are encrypted and cannot be identified as originating from the wallet provider when a transaction has been added to a mempool or mined.

(I don’t think any wallet clients have implemented the second criterion yet.)

**Comment by kristovatlas** [comment]
reword:

> The wallet provider sends out-of-band notifications which are encrypted and cannot be identified as originating from the wallet provider when a transaction has been added to a mempool or mined.

to:

> The wallet provider sends out-of-band notifications which are encrypted and cannot be identified as originating from the wallet provider when notifying the user about a transaction.

**Comment by kristovatlas** [comment]
reword:

> The wallet provider does not send out-of-band notifications to the user when a transaction has been added to a mempool or mined that involves the user’s funds.

to:

> Number of clicks to prevent the wallet provider from sending out-of-band notifications to the user about a transaction.

**Comment by dcousens** [comment]
ACK on both

**Comment by kristovatlas** [comment]
All criteria related changes are satisfied in the latest merged PR.
