### ISSUE TITLE
Attack/Countermeasures: Onion server

### ISSUE THREAD

**Issue by kristovatlas** [OpenBitcoinPrivacyProject/wallet-ratings#45]
Attack: (need to clarify) attacker performs one of various privacy attacks on users who use exit nodes, or security-compromising mitm attacks on users connecting via Exit nodes. 

Countermeasure: If the client must connect to a server, the wallet provider provides an onion server to connect to.

Criteria: Count number of clicks to connect to onion server. If no server needed, gets full credit.

**Comment by kristovatlas** [comment]
A few sites that provide .onion servers: Blockchain.info, coinkite.

We could also factor % uptime into the score.

**Comment by JeremyRand** [comment]
In the specific attack case of a MITM attack, TLS with a pinned key is just as good as, if not better than, a .onion domain.  (Tor hidden services currently use significantly weaker crypto than most current TLS implementations.)  Of course, TLS doesn't provide anonymity (by itself), but you can connect to servers that use TLS via Tor exits, which provides roughly the same anonymity to the client.

**Comment by kristovatlas** [comment]
pinned certificate is pretty good, though you will need to pin the certificate to a variety of browsers which is practically difficult.

**Comment by JeremyRand** [comment]
For a browser-based client, then yes, there would be a difficulty in getting most browsers to use the pin.  However, if it's a non-browser client that connects to an API server (e.g. something like Electrum), then it's easy to pin a TLS pubkey in that client.

**Comment by kristovatlas** [comment]
True fact.

**Comment by justusranvier** [comment]
There are more than one attacker and more than one attacker to consider:
- The wallet provider should learn as little as possible about their users
- The users' ISPs should learn as little as possible about the users. This includes, not just information that should be encrypted like a particular user's balance, but also the fact that they are using a certain wallet provider at all.

Pinned TLS certificates are a partial solution. They are certainly needed if there is no native onion server for the service. 

In the case of a native onion server, a hard-coded hidden service URL is functionally equivalent to a pinned certificate so they are redundant in that case.

**Comment by JeremyRand** [comment]
@justusranvier Would you consider pinned TLS certs combined with using Tor exit relays, to be not as good as a .onion domain?  If so, can you elaborate on that?  Seems to me that if anything, Tor exits give you anonymity that's just as good as .onion, and pinned TLS actually is stronger crypto than .onion.  Am I missing something in the threat model here?

**Comment by justusranvier** [comment]
In terms of privacy, they are probably both equivalent.

In some cases there might be usability and reliability advantages of hidden services.

**Comment by kristovatlas** [comment]
There are actually some differences in privacy due to the way that HSDirs work in Tor, but it's a bit nuanced.

**Comment by kristovatlas** [comment]
If she's available, @isislovecruft would probably be able to explain the privacy differences between an HS and a clearnet server with client-pinned SSL certs.

**Comment by kristovatlas** [comment]
new attack (network observer): ~ perform transport-layer attack on connection between client and server/peer and modify traffic.

countermeasure: pin the expected server certificate in the client -- some form of SSL cert may work here as well

**Comment by kristovatlas** [comment]
Currently in the model:
- Network observer attack: Perform a transport-level MITM attack on a connection between the wallet and a source of server to obtain PII and/or insert malicious code into the communication between wallet and server
  - CM32: Pin the expected public key/certificate in the client to prevent successful MITM attacks
    - (no criteria)

Suggested new criterion:

> The wallet client only connects to remote servers using public keys or secret pre-shared keys to encrypt data in transit.

**Comment by kristovatlas** [comment]
Let's re-word the countermeasure:

> Network communication begins with authenticating the server or peer before encrypting subsequent traffic

**Comment by kristovatlas** [comment]
Let's have these two criteria under that reworded countermeasure:
1. The wallet client uses a pinned X509 certificate or public key for TLS encryption of traffic
2. The wallet client uses a pre-shared key to authenticate the server
