### ISSUE TITLE
Transaction details => API lookup

### ISSUE THREAD

**Issue by kristovatlas** [OpenBitcoinPrivacyProject/wallet-ratings#46]
Most wallets use a web API to lookup transaction details, or simply provide a hyperlink to a block explorer to the user. What privacy protections are appropriate here?

**Comment by kristovatlas** [comment]
scenario: operator of a block explorer waits for new txs, notes which IP address does a lookup on the tx first. likely to be either sender or receiver.

**Comment by kristovatlas** [comment]
new attack: ~ correlate IP address to likely tx participant by observing block explorer monitoring requests for details about a specific, recent tx

**Comment by kristovatlas** [comment]
proposed countermeasure: do not query 3rd party API for balance
proposed countermeasure: do not link to block explorer from GUI
proposed countermeasure: connect to block explorer via Tor (or equivalent) by default
proposed countermeasure: connect to block explorer via Tor (or equivalent) by default and use a new connection context for each query.

proposed criteria: score is inverse relationship to minimum number of clicks it takes for user to view transaction details or address details in a block explorer, starting from the default home screen of the wallet client.

**Comment by kristovatlas** [comment]
> proposed countermeasure: connect to block explorer via Tor (or equivalent) by default and use a new connection context for each query.

this relates to a different kind of attack -- grouping addresses to a single owner

**Comment by justusranvier** [comment]
countermeasure: "Avoid performing queries to third party services regarding specific transactions in a manner which reveals the IP address of the user"

**Comment by kristovatlas** [comment]
some criteria

```
Do not query 3rd party API for balance queries AND (one of the following)   
Do not link to block explorer from GUI OR   
Connect to block explorer via Tor (or equivalent)
```

**Comment by kristovatlas** [comment]
In the model currently:
- Network observer attack: Correlate an IP address to a likely transaction participant by monitoring for queries (to a block explorer, etc.) about specific recent transactions
  - Countermeasure CM31: Avoid performing queries to third party services regarding specific transactions in a manner which reveals the IP address of the user
    - (no criteria)

Existing criteria in the model that might fit here:
- OBPPV3/CR25 (e9d26b9622bbc535f5625505cf2e4924847058b97e055323a332f82ed24bf067): Blockchain data is obtained from a local copy of the blockchain
- OBPPV3/CR24 (d594bb5bc8f342b8794072a48bffe36cdfe142dd19a4773e46abbfc931083a9f): Number of clicks required by user to configure the client to query blockchain data without leaking his machine's identity over the network
- OBPPV3/CR29 (39a6395c7e93ac44cde490d1970b0b6fb1dd812f2d8c5c83fff7e6f8839afd69): The wallet client provides visual indication and displays the user's apparent IP address if blockchain data is not being obtained through an anonymizing network
- OBPPV3/CR27 (16b6ab28cba33110aebdac4a1c1309a5c31a599f31e641d9a46d718f1ad31db1): Blockchain data is queried via a method that matches a fraction of the blockchain beyond the addresses belonging to the wallet)

**Comment by kristovatlas** [comment]
Let's make a duplicate of CR27 above but use "transactions" instead of "addresses"

The other 3 can also be listed under CM31.

**Comment by kristovatlas** [comment]
Comment to CR25: "A local copy" may also be remote but under the user's private control.

**Comment by kristovatlas** [comment]
All of the criteria in this issue have now been merged into a working branch.

**Comment by dcousens** [comment]
Do we have any attacks that correlate users looking up their own (unpopular) addresses,  whenever,  allowing block explorers to track them?
In terms of how it relates to wallet,  if the wallet encourages a link to a block explorer at all that doesn't use probabilistic filters... even if the application itself does.

**Comment by dcousens** [comment]
Maybe it could warn/discourage users "copying" addresses/transactions out of the application etc
