### ISSUE TITLE
Breaking privacy by identifying payed and change amounts

### ISSUE THREAD

**Issue by SergioDemianLerner** [OpenBitcoinPrivacyProject/wallet-ratings#5]
In Change Addresses Quality, there is another item that should be more precisely listed.
You can find out which is the change address by taking into account that, if the software tries to optimize the transaction size and it tries to use as little inputs as possible, and more than one inputs is chosen, then the following conditions that leak information will hold:

If inputs are I(1) .. I(N), and outputs are O(1) .. O(M), and O(1) is the payed amount, then:
O(i) < I(j) for i>1 and 1<=j<=M
O(1) >= I(j) for 1<=j<=M and more precisely..
O(1) >= Sum(O(j) for 1<=j<=M ) - Min(O(j) for 1<=j<=M )

So either you always use a single input or you must add more inputs to make sure that:
A. O(i) < Sum(O(j) for 1<=j<=M ) - Min(O(j) for 1<=j<=M )
B. O(i) >= I(j) for i>1 and 1<=j<=M

This greedy algorithm to find such input/outputs seems to preserve change index privacy but does not preserve amount privacy: add random inputs until the input amount >= payed amount \* 2.

I wonder if there is polynomial which at the same time:
- Preserves change index privacy
- Preserves payed amount privacy
- Minimizes the transaction size.

Maybe the decision problem is NP-complete.

So the new quality item could be:
The size and number of INPUTS and OUTPUTS are chosen to make the change outputs indistinguishable from the desired spend output by the input/output amounts relation?

**Comment by kristovatlas** [comment]
This is excellent input. Thank you, @SergioDemianLerner. @justusranvier will author a pull request to reflect this for Q1.
