### ISSUE TITLE
Attack: Wallet Provider can correlate multiple accounts with cookies or other browser fingerprint

### ISSUE THREAD

**Issue by kristovatlas** [OpenBitcoinPrivacyProject/wallet-ratings#52]
Privacy with respect to the segregation of multiple accounts may be harmed for wallets that use web-based lookups by setting a cookie value that remains constant between balance lookups / tx broadcasts, or which remains constant/linkable between logins.

**Comment by kristovatlas** [comment]
new attack (network attacker): ~client fingerprint correlates different network connections to link addresses from different accounts.

**Comment by kristovatlas** [comment]
See also: #40

**Comment by kristovatlas** [comment]
Justus added countermeasure.

**Comment by kristovatlas** [comment]
Currently we have only one Network observer attack that would apply to this:
- Network observer attack: Temporally correlate activity of a specific wallet across different connection sessions by observing idiosyncratic client wallet behavior which acts as a unique fingerprint
  - Countermeasure CM30: Avoid communicating state-based information to other entities which could be used to uniquely identify the client

~~I'm not very satisfied with the wording of this attack in capturing the intent of this issue.~~

~~For example, if my web wallet client always sends an HTTP cookie "USER=USER1234" with each HTTP request, this doesn't have anything to do with temporal correlation. Do we need a separate attack for this, or can we just generalize the wording of the current one? (I prefer the latter).~~

**Comment by kristovatlas** [comment]
Proposed criterion: The wallet client does not send stateful information in messages that persists between connection contexts.

Comment for JSON: "Stateful information includes a unique browser fingerprint, HTTP cookies, HTTP headers, etc."

I will add this in a PR.

**Comment by kristovatlas** [comment]
We should also list this criterion under II A, OBPPV3/CM61 "Perform multiple queries for blockchain data in a way that makes it difficult to correlate the queries with one another"

**Comment by kristovatlas** [comment]
I plan to re-word this attack

> Temporally correlate activity of a specific wallet across different connection sessions by observing idiosyncratic client wallet behavior which acts as a unique fingerprint

to 

> Correlate activity of a specific wallet across different connection sessions by observing idiosyncratic client wallet behavior which acts as a unique fingerprint

for more clarity.

**Comment by kristovatlas** [comment]
All of the criteria-related changes have been reflected in the merged PR.

**Comment by dcousens** [comment]
ACK
