### ISSUE TITLE
Better define criteria for open source code -- what if server end of client/server model is closed?

### ISSUE THREAD

**Issue by kristovatlas** [OpenBitcoinPrivacyProject/wallet-ratings#54]
It is more difficult if not impossible for a user to verify that wallet providers are applying the privacy countermeasures they claim to if the server code is closed source.

**Comment by JeremyRand** [comment]
Even if the server operator releases source code, it's probably impossible to verify that the source code on their server is the same as the source code that they released.  If the client side code isn't ensuring privacy against a malicious server, then the user has to trust that the server isn't malicious.

This topic is still relevant though, in the sense that a non-malicious server operator may end up with more secure code if their code is open-source.  Also, if the server code is open-source, then the user could pick a server operator who is trusted and have them run the code.

**Comment by kristovatlas** [comment]
Yes, good points.

**Comment by kristovatlas** [comment]
There may be some way for a server to prove good behavior through advanced cryptography (pre-commits? running encrypted code that client provides?) but this isn't worth thinking about too much at present.

**Comment by justusranvier** [comment]
In general, I think the best approach is to assume that which can't be verified is potentially malicious.

Absent future alien technology that lets clients know what exactly is running on the server, the model should consider that everything not under the control of the user is a potential attacker.
