### ISSUE TITLE
Number of transaction signers is leaked to blockchain in redeem script (e.g. traditional P2SH multisig)

### ISSUE THREAD

**Issue by kristovatlas** [OpenBitcoinPrivacyProject/wallet-ratings#59]
Countermeasure: Use P2PKH address, single signer or threshold signature.

**Comment by kristovatlas** [comment]
attacker: blockchain observer

**Comment by kristovatlas** [comment]
Attack: ~ Observer number of signers based on redeem script.

**Comment by kristovatlas** [comment]
@justusranvier has already included a countermeasure for this in his PR:

> Sign transactions using techniques that do not reveal the number of signers or keys involved in producing the signature.  

Only a criterion remains to be added.

**Comment by kristovatlas** [comment]
This applies to two attacks.

1)
https://github.com/OpenBitcoinPrivacyProject/threat-model-scoring-system/blob/0b3603fb0e7dce5d6de19ca5ab1e93f507646ce0/obpp3.json

```
Blockchain observer: Link outputs in a transaction to a single entity by detecting which output is a change output
```

```
"numeral": "3",
"id": "OBPPV3/CM64",
"description": "The composition of transaction output scripts and ECDSA signatures does not reveal information regarding counterparty ownership of outputs",
```

new proposed criteria:
~~> All output scripts have the same number of keys~~

> All output scripts structures must match
> 
> Wallet warns the user of a likely loss of privacy when sending to a P2SH address and the clients have not negotiated a common redeem script structure for spending transaction outputs.

2) So under this attack:

```
"numeral": "F",
                    "name": "Link related outputs and transactions by observing the m and n parameters of multisig transactions",
                    "weight": 0,
                    "nonce-id": "1e772699fb8f43f7e5f82899c32b5db21939965223f29391f057b0063056d241",
```

Also CM64

but this the only criterion:

> All output scripts have the same number of keys

**Comment by dcousens** [comment]
These aren't related to outputs though,  P2SH is only revealed on an input?   Or are we assuming exposure?

**Comment by dcousens** [comment]
What about the mixing,  just in general,  of P2SH and P2PKH.
This is more often the issue.

Or a green address 2-of-3 being sent to a BitGo 2-of-2.
The issue there is the resultant outputs (that is, _after exposure_) have differing key-structures to satisfy.
(2-of-2 vs 2-of-3).

They also might have identifiable keys being used.

Sometimes this isn't _even_ possible to fix,  because the recipient specifies it and you have no idea if their P2SH is multisig, or a P2SH(P2PKH)...

> All output scripts have the same number of keys

Certainly doesn't make much sense when ordering of keys is also important... if 1 party always orders but the other doesn't.

**Comment by kristovatlas** [comment]
We may consider dropping attack "F" as a duplicate of "B"

**Comment by kristovatlas** [comment]
Added new criteria for "B" in the comment above

**Comment by kristovatlas** [comment]
Would like to check with @justusranvier on removing "F"

**Comment by kristovatlas** [comment]
No new discussion on this -- I will create a PR to remove the aforementioned attack.

**Comment by kristovatlas** [comment]
All criteria related changes are now reflected in (a) merged PR(s).
