### ISSUE TITLE
Breaking privacy in payed amounts by identifying fiat currency amounts

### ISSUE THREAD

**Issue by SergioDemianLerner** [OpenBitcoinPrivacyProject/wallet-ratings#6]
Other way to identify payed amounts that were converted from fiat to BTC is to look up the historical data of BTC/fiat prices and try to find conversions where the fiat value has a small number of decimal digits. Trade prices differ from exchange to exchange, but still you could check against several ones. Current BTC volatility probably blurs the price...but maybe not in the future.

The only way to defeat this would be by adding random BTC values to the payed amount, but the counterparty (e.g. a merchant) must be willing to accept a different amount than the one agreed upon.

**Comment by kristovatlas** [comment]
Good observation. Thankyou, @SergioDemianLerner. I believe this boils down to the "significand attack." Privacy-centric altcoins have tried to tackle this problem, and generally addressed it with uniform denominations and careful handling of change. We'd like to take some more time to think about how it would be reasonably dealt with by a wallet and incorporate into the Q2 version of this rating document.

**Comment by justusranvier** [comment]
This attack is covered by the "One or more change outputs are created which are close to the value of the desired spend?" criteria.

If wallets do this, then it won't be possible to use exchange rate comparisons to distinguish between the spend output and the change output.
