### ISSUE TITLE
Attack: Attacker modifies code that is pushed to client before user can review

### ISSUE THREAD

**Issue by kristovatlas** [OpenBitcoinPrivacyProject/wallet-ratings#60]
Attack: Attacker modifies source code of client, and update is pushed to the client:

Countermeasure: Client is notified before a software update takes place, and has opportunity to intervene before wallet private keys or meta data are decrypted.

Countermeasure: Application binaries (or source code for interpreted languages) are cryptographically signed by the wallet provider, and the user has the opportunity to verify the signature before private keys or wallet metadata are decrypted.

**Comment by jim618** [comment]
An example of this IRL is the update process for MultiBit HD.
This takes the following steps:
1) User is told at startup that there is a new version and given the opportunity to download the installer or not.
2) If user chooses to download installer the Installer downloads.
3) User is asked if they want to run it now, or not.
4) If user does not run immediately, they can check the SHA256 hash of the installer, the PGP signature or (Windows) the authenticode signing or (Mac) the Apple developer id signing.

**Comment by kristovatlas** [comment]
Countermeasure: Client is self-updating, but verifies the update has been cryptographically signed by a trusted key before installing.

**Comment by kristovatlas** [comment]
This attack is a duplicate of: "Hide adverse privacy behavior from users by distributing binary versions of the wallet whose behavior differs from versions compiled from the public source code"

**Comment by kristovatlas** [comment]
Aggregating the information here:

Existing attack:

> Hide adverse privacy behavior from users by distributing binary versions of the wallet whose behavior differs from versions compiled from the public source code

Existing countermeasure:

> Provide a deterministic build system that allows users to verify that the binary version they have received was compiled from the public source code

Proposed additional countermeasures under this attack:
1. Notify the user before applying a software update to the client, and provide an opportunity to intervene before wallet private keys or meta data are decrypted.
2. Require developers to cryptographically sign all application binaries (or source code for interpreted languages) provided, and give the user the user has the opportunity to verify the signature before private keys or wallet metadata are decrypted before software updates are applied.
3. Design the wallet client to cryptographically verify updates with a trusted key before installing them.

**Comment by justusranvier** [comment]
Per meeting discussion, the three listed item in the last comment are criteria applying to the existing countermeasures, not new countermeasures.

**Comment by kristovatlas** [comment]
```
#Wallet provider attack 5 of 6
                    numeral: E
                    name: Hide adverse privacy behavior from users by distributing binary versions of the wallet whose behavior differs from versions compiled from the public source code
                    weight: 0
                    nonce-id: 0fbb6308974653bc2d96223b08bd23de3845ae82f46accef5cfd06b711104a41
                    countermeasures: [{
                            numeral: "1"
                            id: OBPPV3/CM55
                            description: Provide a deterministic build system that allows users to verify that the binary version they have received was compiled from the public source code
                            effectiveness: 0
                            criteria: [{
```

**Comment by kristovatlas** [comment]
exiting criteria:

```
numeral: a
                                    id: OBPPV3/CR71
                                    description: A user can produce a compiled version of the application from the public source code that exactly matches the version distributed by the wallet provider
```
this corresponds to 1) above
```
numeral: b
                                    id: OBPPV3/CR120
                                    description: Before applying a software update, the client notifies the user of the udpate and provides an opportunity to intervene before wallet private keys or meta data are decrypted using updated software
```
(todo fix typo s/udpate/update/)

this is 2):
```
 numeral: c
                                    id: OBPPV3/CR121
                                    description: Developers cryptographically sign all application binaries (or source code for interpreted languages) provided, and the client can verify the signature before private keys or wallet metadata are decrypted using updated software
```

this is 3):
```
numeral: d
                                    id: OBPPV3/CR122
                                    description: The wallet client cryptographically verifies all packaged software updates with a pinned public key before automatically updating software
```

Therefore `reorg-to-scoring-system/obpp3.hjson` already satisfies what is discussed in this issue. Closing.

**Comment by kristovatlas** [comment]
https://raw.githubusercontent.com/OpenBitcoinPrivacyProject/threat-model-scoring-system/reorg-to-scoring-system/obpp3.hjson
