### ISSUE TITLE
blockchain attack: shadow change heuristic

### ISSUE THREAD

**Issue by kristovatlas** [OpenBitcoinPrivacyProject/wallet-ratings#82]
A blockchain observer can perform cluster analysis to determine that the sender for a given transaction is using an HD wallet. Inspecting the outputs, he observes that one goes to an address with a prior transaction history, and one does not. Since HD wallets are very likely to create a new change address for each send, he can distinguish the change address with a high probability based on the compared history of output addresses/public keys.

This presumably already falls under this attack: "Link outputs in a transaction to a single entity by detecting which output is a change output"

troll countermeasure: if sending to an address that is reused, use a reused change address.

actual countermeasure: warn the user when she is about to send to a reused address that her change address may be outed. (this is an existing criteria, but this would be a new countermeasure that it could apply to.)

this is a nice example of how a transaction participants' address reuse can directly negatively impact your privacy, whether the reuser is a sender or receiver.

**Comment by kristovatlas** [comment]
This idea was new to me via these slides: http://jonasnick.github.io/slides/2016-zurich-meetup.pdf

Hat tip to @jonasnick.

**Comment by kristovatlas** [comment]
countermeasure: a multi-sender transaction such as a CoinJoin may make it more difficult to connect revealed change outputs with specific inputs addresses.

**Comment by kristovatlas** [comment]
The existing attack is:

> Link outputs in a transaction to a single entity by detecting which output is a change output 

This existing countermeasure for a different attack should now be applied to the above attack:

> Avoid address reuse

**Comment by kristovatlas** [comment]
In an earlier comment I wrote:

> countermeasure: a multi-sender transaction such as a CoinJoin may make it more difficult to connect revealed change outputs with specific inputs addresses.

This is true, but isn't a new concern. You can construct your CoinJoin or non-CoinJoin transaction in such a way to obscure which outputs are change, but that is covered in this existing countermeasure:

> Use multiple change outputs, and intentionally set the value of some outputs to values that resemble plausible spends

CoinJoin may break the linkage between a change output and a specific set of inputs -- if constructed very carefully, so carefully that today it would be uncharacteristic of CoinJoins -- but I think this is already covered elsewhere in the threat model.

**Comment by kristovatlas** [comment]
If https://github.com/kristovatlas/wallet-ratings/commit/8351de178ed1429623d07170f369edcfb494d478 is merged, then all countermeasures for this issue are satisfied.

**Comment by dcousens** [comment]
As captured in https://github.com/OpenBitcoinPrivacyProject/threat-model-scoring-system/blob/a67a63a73353a3d9054a493cc79d3dd3f06af38b/obpp3.json#L20, ACK `Avoid reuse of identifiable script elements`

**Comment by kristovatlas** [comment]
the other general countermeasure idea here is to blend in with your counterparty (H/T @dcousens) but in this case that would require you to reuse an address for your change address and/or reuse another address in the next transaction (if your counterparty spends outputs first) in order to blend in; since that clearly has other negative effects, we won't bother to put it in the threat model for now.

**Comment by kristovatlas** [comment]
I will make a PR to specify the relevant criteria @dcousens and I discussed tonight.

**Comment by kristovatlas** [comment]
Looks like all of the criteria we talked about are listed for the relevant attack now: https://github.com/OpenBitcoinPrivacyProject/threat-model-scoring-system/blob/a67a63a73353a3d9054a493cc79d3dd3f06af38b/obpp3.json#L124-L191
